#! /bin/bash
# ===== PBS Options ========
#PBS -N "2k_atobGan"
#PBS -q copperhead
#PBS -l walltime=100:00:00
#PBS -l mem=128GB 
#PBS -l nodes=1:ppn=8:gpus=1:gtx1080ti

module load pytorch/0.4.0-anaconda3-cuda9.2-sm6.1
cd /scratch/shuang9/pix2pixHD/
python3 train.py --name gray2color_2048p --dataroot ./datasets/color2k/ --label_nc 0 --no_instance --netG local --num_D 3 --ngf 32 --niter_fix_global 20 --resize_or_crop crop --fineSize 1024 --load_pretrain checkpoints/pretrain_model/ --tf_log
